language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - mysql -e "create database IF NOT EXISTS carbon_fields_tests;" -uroot
  - bash tests/bin/install.sh carbon_fields_tests root '' localhost $WP_VERSION

script: phpunit --coverage-clover=./tmp/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tmp/clover.xml